// Yangon Airport shops and dining data
const shops = [
    {'name': 'Shop Dine', 'image_url': 'https://yangonairport.aero/images/shopdine/shop-dine-01.jpg'},
    {'name': 'Cavalli Class', 'image_url': 'https://yangonairport.aero/images/shopdine/cavalli-class.jpg'},
    {'name': 'Coach', 'image_url': 'https://yangonairport.aero/images/shopdine/coach.jpg'},
    {'name': 'Dun 18', 'image_url': 'https://yangonairport.aero/images/shopdine/dun-18-01.jpg'},
    {'name': 'Ermen', 'image_url': 'https://yangonairport.aero/images/shopdine/ermen-01.jpg'},
    {'name': 'Fossil', 'image_url': 'https://yangonairport.aero/images/shopdine/fossil-01.jpg'},
    {'name': 'Furla', 'image_url': 'https://yangonairport.aero/images/shopdine/furla-01.jpg'},
    {'name': 'Galleria', 'image_url': 'https://yangonairport.aero/images/shopdine/galleria-01.jpg'},
    {'name': 'Kate', 'image_url': 'https://yangonairport.aero/images/shopdine/kate-01.jpg'},
    {'name': 'Kipling', 'image_url': 'https://yangonairport.aero/images/shopdine/kipling-01.jpg'},
    {'name': 'Longines', 'image_url': 'https://yangonairport.aero/images/shopdine/longines-01.jpg'},
    {'name': 'Mandarinaa', 'image_url': 'https://yangonairport.aero/images/shopdine/mandarinaa-01.jpg'},
    {'name': 'Mont', 'image_url': 'https://yangonairport.aero/images/shopdine/mont-01.jpg'},
    {'name': 'Phwar', 'image_url': 'https://yangonairport.aero/images/shopdine/phwar-01.jpg'},
    {'name': 'Samsonite', 'image_url': 'https://yangonairport.aero/images/shopdine/samsonite-01.jpg'},
    {'name': 'Shanghai', 'image_url': 'https://yangonairport.aero/images/shopdine/shanghai-01.jpg'},
    {'name': 'Swar', 'image_url': 'https://yangonairport.aero/images/shopdine/swar-01.jpg'},
    {'name': 'Ladychin', 'image_url': 'https://yangonairport.aero/images/shopdine/ladychin-02.jpg'},
    {'name': 'Tumi', 'image_url': 'https://yangonairport.aero/images/shopdine/tumi-01.jpg'},
    {'name': 'Versace', 'image_url': 'https://yangonairport.aero/images/shopdine/versace-01.jpg'},
    {'name': 'Bon', 'image_url': 'https://yangonairport.aero/images/shopdine/bon-01.jpg'},
    {'name': 'Cafe', 'image_url': 'https://yangonairport.aero/images/shopdine/cafe-01.jpg'},
    {'name': 'Coffee Bean', 'image_url': 'https://yangonairport.aero/images/shopdine/coffee-bean-01.jpg'},
    {'name': 'Espace', 'image_url': 'https://yangonairport.aero/images/shopdine/espace-01.jpg'},
    {'name': 'Kfc', 'image_url': 'https://yangonairport.aero/images/shopdine/kfc-01.jpg'},
    {'name': 'Mcs', 'image_url': 'https://yangonairport.aero/images/shopdine/mcs-01.jpg'},
    {'name': 'Parison', 'image_url': 'https://yangonairport.aero/images/shopdine/parison-01.jpg'},
    {'name': 'Kzy', 'image_url': 'https://yangonairport.aero/images/shopdine/kzy-01.jpg'},
    {'name': 'Marry', 'image_url': 'https://yangonairport.aero/images/shopdine/marry-01.jpg'},
    {'name': 'Natthoe', 'image_url': 'https://yangonairport.aero/images/shopdine/natthoe-01.jpg'},
    {'name': 'Boon', 'image_url': 'https://yangonairport.aero/images/shopdine/boon-01.jpg'},
    {'name': 'Cafe Corner', 'image_url': 'https://yangonairport.aero/images/shopdine/cafe-corner-01.jpg'},
    {'name': 'Espace', 'image_url': 'https://yangonairport.aero/images/shopdine/espace-01.jpg'},
    {'name': 'Jdonuts', 'image_url': 'https://yangonairport.aero/images/shopdine/jdonuts-01.jpg'},
    {'name': 'Jj', 'image_url': 'https://yangonairport.aero/images/shopdine/jj-01.jpg'},
    {'name': 'Kfc', 'image_url': 'https://yangonairport.aero/images/shopdine/kfc-01.jpg'},
    {'name': 'Krispy', 'image_url': 'https://yangonairport.aero/images/shopdine/krispy-01.jpg'},
    {'name': 'Lotteria', 'image_url': 'https://yangonairport.aero/images/shopdine/lotteria-01.jpg'},
    {'name': 'Myanmar Life', 'image_url': 'https://yangonairport.aero/images/shopdine/myanmar-life-02.jpg'},
    {'name': 'Mcs', 'image_url': 'https://yangonairport.aero/images/shopdine/mcs-01.jpg'},
    {'name': 'Parison', 'image_url': 'https://yangonairport.aero/images/shopdine/parison-01.jpg'},
    {'name': 'Yakun', 'image_url': 'https://yangonairport.aero/images/shopdine/yakun-01.jpg'},
    {'name': 'Yangoon', 'image_url': 'https://yangonairport.aero/images/shopdine/yangoon-01.jpg'}
];